apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: idp-argo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - git:
        repoURL: https://github.com/Phumitada/IDP-Manifests
        revision: main
        directories:
        - path: app/*
        - path: database/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Phumitada/IDP-Manifests
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true