apiVersion: paas.internal/v1
kind: Application
metadata:
  name: order-system-api
spec:
  image: ghcr.io/phumitada/order-system-api:b2caff3
  port: 5001
  imagePullSecret: ghcr-secret
  databaseRef:
    - postgres-test
    - redis-test
  domain: order-system-api.phumitada.com